#-----------------------------------------------------------------
# Generated by makemake.pl. Type 'makemake.pl' to see the usage
#-----------------------------------------------------------------
PROG =	trajman

SRCS =	module_input.F90 module_kinds.f90 module_readtraj.f90 \
	module_trajop.f90 module_util.f90 trajman.f90

OBJS =	module_input.o module_kinds.o module_readtraj.o module_trajop.o \
	module_util.o trajman.o

LIBS =  #/usr/lib64/liblapack.so.3

INCLUDES = -I/data/jon/src/LAPACK95/lapack95_modules/ 
#LIBSPATH = -L/usr/common/sprng2.0/lib
LIBSPATH = /data/jon/src/LAPACK95/lapack95.a /usr/lib64/liblapack.so.3 
CC = gcc
CFLAGS = -03
F90 = gfortran 
#F90 = ifort 
FFLAGS =  -O3 
F90FLAGS =  -O3 -g 
FC90FLAGS = -D "CINFO='$$(date)'" $(F90FLAGS)
LDFLAGS = 

all: $(PROG)

$(PROG): $(OBJS)
	$(F90) $(LDFLAGS) -o $@ $(OBJS) $(LIBSPATH) $(LIBS)
clean:
	rm -f $(PROG) $(OBJS) *.mod

.SUFFIXES: $(SUFFIXES) .f90 

.f90.o:
	$(F90) $(F90FLAGS) -c $< $(LIBS) $(INCLUDES)

.SUFFIXES: $(SUFFIXES) .f90

.f.o:
	$(F90) $(F90FLAGS) -c $< $(LIBS)

.SUFFIXES: $(SUFFIXES) .F90 

.F90.o:
	$(F90) $(FC90FLAGS) -c $< $(LIBS) $(INCLUDES)

module_input.o: module_kinds.o module_readtraj.o module_util.o
module_readtraj.o: module_kinds.o
module_trajop.o: module_kinds.o
module_util.o: module_kinds.o module_readtraj.o
trajman.o: module_input.o module_kinds.o module_readtraj.o module_trajop.o \
	module_util.o
